swagger: '2.0'
info:
  title: 'ProductClassificationService API'
  version: '1.0'
paths:
  /auth/sign-in:
    post:
      summary: 'Sign In'
      description: 'Sign in and get an access token.'
      tags:
        - 'auth'
      parameters:
        - in: 'body'
          name: 'user_info'
          description: 'User credentials for sign-in.'
          schema:
            $ref: '#/definitions/SignIn'
      responses:
        '200':
          description: 'Successful sign-in'
          schema:
            $ref: '#/definitions/SignInResponse'
  /auth/sign-up:
    post:
      summary: 'Sign Up'
      description: 'Sign up and create a new user.'
      tags:
        - 'auth'
      parameters:
        - in: 'body'
          name: 'user_info'
          description: 'User information for sign-up.'
          schema:
            $ref: '#/definitions/SignUp'
      responses:
        '200':
          description: 'Successful sign-up'
          schema:
            $ref: '#/definitions/User'
  /auth/me:
    get:
      summary: 'Get Current User'
      description: 'Get information about the currently authenticated user.'
      tags:
        - 'auth'
      security:
        - apiKey: []
      responses:
        '200':
          description: 'Successful retrieval of current user'
          schema:
            $ref: '#/definitions/User'
  /billing/points:
    get:
      summary: 'Get User Balance'
      description: 'Get the current balance of the user''s points.'
      tags:
        - 'billing'
      security:
        - apiKey: []
      responses:
        '200':
          description: 'Successful retrieval of user balance'
          schema:
            type: 'integer'
  /billing/deduct:
    post:
      summary: 'Deduct Credits'
      description: 'Deduct credits from the user''s balance for a specific reason.'
      tags:
        - 'billing'
      security:
        - apiKey: []
      parameters:
        - in: 'body'
          name: 'deduction_data'
          description: 'Data for deducting credits.'
          schema:
            $ref: '#/definitions/DeductionData'
      responses:
        '200':
          description: 'Successful deduction of credits'
          schema:
            type: 'boolean'
  /billing/history:
    get:
      summary: 'Get Billing History'
      description: 'Get the billing history of the user.'
      tags:
        - 'billing'
      security:
        - apiKey: []
      responses:
        '200':
          description: 'Successful retrieval of billing history'
          schema:
            type: 'array'
            items:
              $ref: '#/definitions/BillingHistory'
  /predictor/predict/{model_name}:
    post:
      summary: 'Make Prediction'
      description: 'Make a prediction using the specified model.'
      tags:
        - 'predictor'
      parameters:
        - in: 'path'
          name: 'model_name'
          description: 'The name of the model to use for prediction.'
          required: true
          type: 'string'
        - in: 'body'
          name: 'input_data'
          description: 'Input data for making a prediction.'
          schema:
            type: 'object'
      responses:
        '200':
          description: 'Successful prediction'
          schema:
            $ref: '#/definitions/PredictionResult'
  /predictor/prediction/{prediction_task_id}:
    get:
      summary: 'Get Prediction Result'
      description: 'Get the result of a previously made prediction.'
      tags:
        - 'predictor'
      parameters:
        - in: 'path'
          name: 'prediction_task_id'
          description: 'The ID of the prediction task.'
          required: true
          type: 'integer'
      responses:
        '200':
          description: 'Successful retrieval of prediction result'
          schema:
            $ref: '#/definitions/PredictionResult'
definitions:
  SignIn:
    type: 'object'
    properties:
      username:
        type: 'string'
      password:
        type: 'string'
    required:
      - 'username'
      - 'password'
  SignInResponse:
    type: 'object'
    properties:
      token:
        type: 'string'
      token_type:
        type: 'string'
  SignUp:
    type: 'object'
    properties:
      username:
        type: 'string'
      password:
        type: 'string'
      email:
        type: 'string'
    required:
      - 'username'
      - 'password'
      - 'email'
  User:
    type: 'object'
    properties:
      username:
        type: 'string'
      email:
        type: 'string'
  DeductionData:
    type: 'object'
    properties:
      points:
        type: 'integer'
      reason:
        type: 'string'
  BillingHistory:
    type: 'object'
    properties:
      date:
        type: 'string'
      description:
        type: 'string'
  PredictionResult:
    type: 'object'
    properties:
      prediction_result:
        type: 'string'
